### ISSUE TITLE
Unusual values for the 2022-12-18

### ISSUE THREAD

**Issue by lucasrodes** [3dgiordano/covid-19-uy-vacc-data#7]
The file [data/Uruguay.csv](https://raw.githubusercontent.com/3dgiordano/covid-19-uy-vacc-data/main/data/Uruguay.csv) for the 2022-12-187 reports unusual data points:

- 0 for field `total_boosters`.
- 5,897,510 for field `total_vaccinations` (this is roughly -3 million doses compared to previous reported value)

**Comment by 3dgiordano** [comment]
Hi @lucasrodes 
Thanks for reporting the problem.
I'm going to analyze it.

**Comment by 3dgiordano** [comment]
Hi @lucasrodes 

The data inconsistency was resolved.
There was a problem in the data provided by the Ministry of Health from December 11 to December 17.
That failure caused a side effect, a failure to create the data from December 18 to today.

Now the data is already corrected.

The resolution of the data is expected by the ministry from December 11 to 18, but this missing information is not important for what is displayed in Our World In Data.

You can try running the batch again for the vaccination data for Uruguay or wait for tomorrow's batch. The data will be updated correctly.

Thank you @lucasrodes
